insert into weddings (weddingcontactdate,
      fullnames,
      weddingemail,
      weddingphone,
      weddingdate,
      ceremonyinfo,
      receptioninfo,
      guestcount,
      bridalparty,
      colorscheme,
      needpersonal,
      needceremony,
      needreception,
      needcakeflowers,
      needother,
      envision,
      weddingstyle,
      budget,
      pinterest,
      extradetails)
values($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20);